"""Crear tablas iniciales

Revision ID: 6ffdec2ba79e
Revises: a7f3d4c92b10
Create Date: 2026-03-27 15:43:53.197682

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6ffdec2ba79e"
down_revision: Union[str, Sequence[str], None] = "a7f3d4c92b10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
